### ISSUE TITLE
Publish created post to facebook page

### ISSUE THREAD

**Issue by simon-suuk** [simon-suuk/Analizar#17]
A user should be able to publish created post to facebook page

**Comment by draogtech** [comment]
Posting to facebook as a page is successful with facebook-sdk library.

**Comment by simon-suuk** [comment]
Nice work! Submit a Pull Request for this issue. 

1. All you have to do is include the
special keyword syntax "fixes #<issue id>"(in your case => fixes #17) in the body of your Pull Request.

2. And the referenced issue will automatically be closed when the Pull Request is merged
into the development branch.

**Comment by simon-suuk** [comment]
Completed
